---
 
 - name: Update repositories cache and install "haproxy" package
   apt:
    name: haproxy
    update_cache: yes


 - name: Copy HAProxy configuration in place.
   template:
     src: /home/tovmas/Documents/k8s_multi_master_ansible/template/haproxy.cfg.j2
     dest: /tmp/haproxy.cfg


 - name: add parameters to haproxy.conf
   shell: cat /tmp/haproxy.cfg >> /etc/haproxy/haproxy.cfg

 - name: Restart HAproxy
   service:
     name: haproxy
     daemon_reload: yes
     state: restarted